using UnityEngine;
using System.Collections;
using System.Collections.Generic;

//put new entries only in the END of the enum, otherwise the enum will change all the subsequent int values
public enum StageTagEnemy{
	Fruits1,
	Fruits2,
	Fruits3,
	Fruits4,
	Colors1,
	Colors2,
	Colors3,
	Colors4,
	Seasons1,
	Numbers1,
	Numbers2,
	Numbers3,
	Numbers4,
	Tools1,
	Tools2,
	Tools3,
	Tools4,
	Toys1,
	Toys2,
	Media1,
	Media2,
	Media3,
	Transportation1,
	Transportation2,
	Transportation3,
	Transportation4
};

public static class StagesCodes{
	public static Dictionary<StageTagEnemy, string> codes = new Dictionary<StageTagEnemy, string>(){
		{StageTagEnemy.Fruits1, "a" },
		{StageTagEnemy.Fruits2, "b" },
		{StageTagEnemy.Fruits3,"c" },
		{StageTagEnemy.Fruits4,"d" },
		{StageTagEnemy.Colors1,"e" },
		{StageTagEnemy.Colors2,"f" },
		{StageTagEnemy.Colors3,"g" },
		{StageTagEnemy.Colors4,"h" },
		{StageTagEnemy.Seasons1,"i" },
		{StageTagEnemy.Numbers1,"j" },
		{StageTagEnemy.Numbers2,"k" },
		{StageTagEnemy.Numbers3,"l" },
		{StageTagEnemy.Numbers4,"m" },
		{StageTagEnemy.Tools1,"n" },
		{StageTagEnemy.Tools2,"o" },
		{StageTagEnemy.Tools3,"p" },
		{StageTagEnemy.Tools4,"q" },
		{StageTagEnemy.Toys1,"r" },
		{StageTagEnemy.Toys2,"s" },
		{StageTagEnemy.Media1,"t" },
		{StageTagEnemy.Media2,"u" },
		{StageTagEnemy.Media3,"v" },
		{StageTagEnemy.Transportation1,"w" },
		{StageTagEnemy.Transportation2,"x" },
		{StageTagEnemy.Transportation3,"y" },
		{StageTagEnemy.Transportation4,"z" }
	};

	public static Dictionary<string, DifficultyTagEnemy> difficulties = new Dictionary<string, DifficultyTagEnemy>(){
		{"a1", DifficultyTagEnemy.Easy},
		{"b1", DifficultyTagEnemy.Easy},
		{"c1", DifficultyTagEnemy.Normal},
		{"d1", DifficultyTagEnemy.Hard},
		{"e1", DifficultyTagEnemy.Easy},
		{"f1", DifficultyTagEnemy.Easy},
		{"g1", DifficultyTagEnemy.Normal},
		{"h1", DifficultyTagEnemy.Hard},
		{"i1", DifficultyTagEnemy.Normal},
		{"j1", DifficultyTagEnemy.Easy},
		{"k1", DifficultyTagEnemy.Easy},
		{"l1", DifficultyTagEnemy.Normal},
		{"m1", DifficultyTagEnemy.Hard},
		{"n1", DifficultyTagEnemy.Easy},
		{"o1", DifficultyTagEnemy.Easy},
		{"p1", DifficultyTagEnemy.Normal},
		{"q1", DifficultyTagEnemy.Hard},
		{"r1", DifficultyTagEnemy.Easy},
		{"s1", DifficultyTagEnemy.Normal},
		{"t1", DifficultyTagEnemy.Easy},
		{"u1", DifficultyTagEnemy.Easy},
		{"v1", DifficultyTagEnemy.Normal},
		{"w1", DifficultyTagEnemy.Easy},
		{"x1", DifficultyTagEnemy.Normal},
		{"y1", DifficultyTagEnemy.Normal},
		{"z1", DifficultyTagEnemy.Hard},
		{"a2", DifficultyTagEnemy.Easy},
		{"b2", DifficultyTagEnemy.Easy},
		{"c2", DifficultyTagEnemy.Normal},
		{"d2", DifficultyTagEnemy.Hard},
		{"e2", DifficultyTagEnemy.Easy},
		{"f2", DifficultyTagEnemy.Easy},
		{"g2", DifficultyTagEnemy.Normal},
		{"h2", DifficultyTagEnemy.Hard},
		{"i2", DifficultyTagEnemy.Normal},
		{"j2", DifficultyTagEnemy.Easy},
		{"k2", DifficultyTagEnemy.Easy},
		{"l2", DifficultyTagEnemy.Normal},
		{"m2", DifficultyTagEnemy.Hard},
		{"n2", DifficultyTagEnemy.Easy},
		{"o2", DifficultyTagEnemy.Easy},
		{"p2", DifficultyTagEnemy.Normal},
		{"q2", DifficultyTagEnemy.Hard},
		{"r2", DifficultyTagEnemy.Easy},
		{"s2", DifficultyTagEnemy.Normal},
		{"t2", DifficultyTagEnemy.Easy},
		{"u2", DifficultyTagEnemy.Easy},
		{"v2", DifficultyTagEnemy.Normal},
		{"w2", DifficultyTagEnemy.Easy},
		{"x2", DifficultyTagEnemy.Normal},
		{"y2", DifficultyTagEnemy.Normal},
		{"z2", DifficultyTagEnemy.Hard},
		{"a3", DifficultyTagEnemy.Easy},
		{"b3", DifficultyTagEnemy.Easy},
		{"c3", DifficultyTagEnemy.Normal},
		{"d3", DifficultyTagEnemy.Hard},
		{"e3", DifficultyTagEnemy.Easy},
		{"f3", DifficultyTagEnemy.Easy},
		{"g3", DifficultyTagEnemy.Normal},
		{"h3", DifficultyTagEnemy.Hard},
		{"i3", DifficultyTagEnemy.Normal},
		{"j3", DifficultyTagEnemy.Easy},
		{"k3", DifficultyTagEnemy.Easy},
		{"l3", DifficultyTagEnemy.Normal},
		{"m3", DifficultyTagEnemy.Hard},
		{"n3", DifficultyTagEnemy.Easy},
		{"o3", DifficultyTagEnemy.Easy},
		{"p3", DifficultyTagEnemy.Normal},
		{"q3", DifficultyTagEnemy.Hard},
		{"r3", DifficultyTagEnemy.Easy},
		{"s3", DifficultyTagEnemy.Normal},
		{"t3", DifficultyTagEnemy.Easy},
		{"u3", DifficultyTagEnemy.Easy},
		{"v3", DifficultyTagEnemy.Normal},
		{"w3", DifficultyTagEnemy.Easy},
		{"x3", DifficultyTagEnemy.Normal},
		{"y3", DifficultyTagEnemy.Normal},
		{"z3", DifficultyTagEnemy.Hard}
	};
}